name: wplogify

services:
  php:
    build:
      context: .
      dockerfile: PHP.Dockerfile
    container_name: wplogify-php
    depends_on:
      - mysql
    networks:
      - wplogify-network
    environment:
      WORDPRESS_DB_NAME: wplogifydev
      WORDPRESS_DB_USER: wplogifyuser
      WORDPRESS_DB_PASSWORD: freedom
      WORDPRESS_DB_HOST: wplogify-mysql:3306
      WORDPRESS_DB_CHARSET: utf8mb4
      WORDPRESS_DB_COLLATE: utf8mb4_unicode_ci
      WORDPRESS_DEBUG: 1
      TZ: Australia/Brisbane
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_HOME', 'http://wplogify.localhost:8080' );
        define( 'WP_SITEURL', 'http://wplogify.localhost:8080' );
        define( 'WP_DEBUG_DISPLAY', true );
        define( 'WP_DEBUG_LOG', true );
        define( 'WP_ENVIRONMENT_TYPE', 'local' );
    volumes:
      - ../www:/var/www/html
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ../logs/xdebug.log:/var/log/xdebug.log

  nginx:
    image: nginx:1.22.1
    container_name: wplogify-nginx
    depends_on:
      - php
      - mysql
    networks:
      - wplogify-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../logs/nginx:/var/log/nginx
      - ../www:/var/www/html
    ports:
      - "8080:80"

  mysql:
    build:
      context: .
      dockerfile: MySQL.Dockerfile
    container_name: wplogify-mysql
    networks:
      - wplogify-network
    environment:
      MYSQL_ROOT_PASSWORD: freedom
      MYSQL_DATABASE: wplogifydev
      MYSQL_USER: wplogifyuser
      MYSQL_PASSWORD: freedom
    ports:
      - "3307:3306"
    volumes:
      - ../mysql:/var/lib/mysql

networks:
  wplogify-network:
    name: wplogify-network
    driver: bridge
