name: wplogify

services:
  php:
    build:
      context: .
      dockerfile: PHP.Dockerfile
    container_name: wplogify-php
    depends_on:
      - mysql
    networks:
      - wplogify-network
    environment:
      WORDPRESS_DB_NAME: wplogifydev
      WORDPRESS_DB_USER: wplogifyuser
      WORDPRESS_DB_PASSWORD: freedom
      WORDPRESS_DB_HOST: wplogify-mysql:3306
      WORDPRESS_DB_CHARSET: utf8mb4
      WORDPRESS_DB_COLLATE: utf8mb4_unicode_ci
      WORDPRESS_DEBUG: 1
      TZ: Australia/Brisbane
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_HOME', 'http://wplogify.localhost:8083' );
        define( 'WP_SITEURL', 'http://wplogify.localhost:8083' );
        define( 'WP_DEBUG_DISPLAY', false );
        define( 'WP_DEBUG_LOG', true );
        define( 'WP_ENVIRONMENT_TYPE', 'local' );
    volumes:
      - ../www:/var/www/html
      - ../log/php:/var/log

  nginx:
    build:
      context: .
      dockerfile: Nginx.Dockerfile
    container_name: wplogify-nginx
    depends_on:
      - php
    networks:
      - wplogify-network
    ports:
      - "8083:80"
    volumes:
      - ../www:/var/www/html
      - ../log/nginx:/var/log/nginx

  mysql:
    build:
      context: .
      dockerfile: MySQL.Dockerfile
    container_name: wplogify-mysql
    networks:
      - wplogify-network
    environment:
      MYSQL_ROOT_PASSWORD: freedom
      MYSQL_DATABASE: wplogifydev
      MYSQL_USER: wplogifyuser
      MYSQL_PASSWORD: freedom
    ports:
      - "3307:3306"
    volumes:
      - mysql-volume:/var/lib/mysql

networks:
  wplogify-network:
    name: wplogify-network
    driver: bridge

volumes:
  mysql-volume:
    name: wplogify-mysql-volume
