FROM wordpress:6.5.5

# Switch to the root user. We should be already, but just in case.
USER root

# Install the MySQL extension as root.
RUN docker-php-ext-install mysqli

# Change ownership of site files to www-data.
RUN chown -R www-data:www-data /var/www/html

# Switch to the non-root user.
USER www-data
