<?php
/**
 * Contains the Menu_Item_Utility class.
 *
 * @package Logify_WP
 */

namespace Logify_WP;

/**
 * Class Logify_WP\Menu_Item_Utility
 *
 * Provides methods for working with menu items.
 */
class Menu_Item_Utility extends Object_Utility {

	// =============================================================================================
	// Implementations of base class methods.

	/**
	 * Check if a nav menu item exists.
	 *
	 * @param int|string $post_id The post ID of the navigation menu item.
	 * @return bool True if the object exists, false otherwise.
	 */
	public static function exists( int|string $post_id ): bool {
		return Post_Utility::exists( $post_id );
	}

	/**
	 * Get a nav menu item by ID.
	 *
	 * If the object isn't found, null will be returned. An exception will not be thrown.
	 *
	 * @param int|string $post_id The post ID of the navigation menu item.
	 * @return mixed The post object or null if not found.
	 */
	public static function load( int|string $post_id ): mixed {
		return Post_Utility::load( $post_id );
	}

	/**
	 * Get the name of a nav menu item. This will be equal to the name of the linked object.
	 *
	 * @param int|string $post_id The post ID of the navigation menu item.
	 * @return string The name, or null if the object could not be found.
	 */
	public static function get_name( int|string $post_id ): ?string {
		// Load the menu item.
		$menu_item = self::load( $post_id );

		// If the menu item doesn't exist, return null.
		if ( ! $menu_item ) {
			return null;
		}

		// Get the menu item details.
		$details = self::get_menu_item_details( $post_id );

		// If we don't have details, default to the menu item's post title.
		if ( ! $details ) {
			return $menu_item->post_title;
		}

		// Return the menu item name.
		return match ( $details['_menu_item_type'] ) {
			'post_type' => Post_Utility::get_name( $details['_menu_item_object_id'] ),
			'taxonomy'  => Term_Utility::get_name( $details['_menu_item_object_id'] ),
			'custom'    => $menu_item->post_title
		};
	}

	/**
	 * Get the core properties of a nav menu item, for logging.
	 *
	 * @param int|string $post_id The post ID of the navigation menu item.
	 * @return ?Property[] The core properties of the menu item, or null if not found.
	 */
	public static function get_core_properties( int|string $post_id ): ?array {
		global $wpdb;

		// Get the menu item details.
		$details = self::get_menu_item_details( $post_id );

		// If we don't have details, return an empty array.
		if ( ! $details ) {
			return null;
		}

		// Build the array of properties.
		$props = array();

		// Link.
		Property_Array::set( $props, 'link', $wpdb->posts, self::get_linked_object( $post_id ) );

		// Convert the menu item details to properties.
		foreach ( $details as $key => $value ) {
			Property_Array::set( $props, $key, $wpdb->postmeta, $value );
		}
		return $props;
	}

	/**
	 * Return HTML referencing a navigation menu item.
	 *
	 * As opposed to other object types, links returned by this method link to the linked object,
	 * which can be a page, post, category, or custom URL.
	 *
	 * @param int|string $post_id  The post ID of the navigation menu item.
	 * @param ?string    $old_name The name of the object at the time of the event.
	 * @return string The link HTML.
	 */
	public static function get_tag( int|string $post_id, ?string $old_name = null ): string {
		// Get the linked object.
		$linked_object = self::get_linked_object( $post_id );

		// If we have a string, it's an HTML tag, so we can just return it.
		if ( is_string( $linked_object ) ) {
			return $linked_object;
		}

		// If we have an object reference we must check the object exists, otherwise we won't be
		// able to get it's name and hence a fallback tag will be generated by
		// Post_Utility::get_tag() or Term_Utility::get_tag().
		if ( $linked_object instanceof Object_Reference && $linked_object->exists() ) {
			return $linked_object->get_tag();
		}

		// Make a backup name if necessary.
		if ( ! $old_name ) {
			$old_name = "Navigation Menu Item $post_id";
		}

		// Return a span.
		return "<span class='logify-wp-deleted-object'>$old_name (deleted)</span>";
	}

	// =============================================================================================
	// Additional methods.

	/**
	 * Get the menu item details.
	 *
	 * @param int $post_id The post ID of the navigation menu item.
	 * @return ?array The menu item details or null if not found.
	 */
	public static function get_menu_item_details( int $post_id ): ?array {
		// Get the meta data for the post.
		$meta = get_post_meta( $post_id );

		// Make sure we have a menu item type.
		if ( ! $meta || ! isset( $meta['_menu_item_type'][0] ) ) {
			return null;
		}

		// Specify the fields we want according to the menu item type.
		$menu_item_type = $meta['_menu_item_type'][0];
		switch ( $menu_item_type ) {
			case 'post_type':
			case 'taxonomy':
				$fields = array(
					'_menu_item_type',
					'_menu_item_object_id',
					'_menu_item_object',
				);
				break;

			case 'custom':
				$fields = array(
					'_menu_item_type',
					'_menu_item_url',
				);
				break;

			default:
				return null;
		}

		// Extract the menu item details.
		$menu_item = array();
		foreach ( $meta as $key => $value ) {
			// Get the properties we want.
			if ( in_array( $key, $fields ) ) {
				// Just take the first value, these are all singular.
				$menu_item[ $key ] = $value[0];
			}
		}

		// Return the menu item details.
		return $menu_item;
	}

	/**
	 * Return a reference to the linked object.
	 *
	 * @param int $post_id The post ID of the navigation menu item.
	 * @return null|string|Object_Reference The link HTML.
	 */
	public static function get_linked_object( int $post_id ): null|string|Object_Reference {
		// Load the navigation menu item.
		$post = Post_Utility::load( $post_id );

		// If the post doesn't exist, return null.
		if ( ! $post ) {
			return null;
		}

		// Get the linked object details.
		$info = self::get_menu_item_details( $post_id );

		// Check we have a menu item type.
		if ( empty( $info['_menu_item_type'] ) ) {
			return null;
		}

		// Return the linked object.
		return match ( $info['_menu_item_type'] ) {
			'post_type' => new Object_Reference( 'post', $info['_menu_item_object_id'] ),
			'taxonomy'  => new Object_Reference( 'term', $info['_menu_item_object_id'] ),
			'custom'    => "<a href='{$info['_menu_item_url']}' class='logify-wp-object' target='_blank'>{$post->post_title}</a>",
			default     => null
		};
	}

	/**
	 * Get the tag for a menu item from an event.
	 *
	 * @param Event $event The event.
	 * @return ?string The tag, or null if not found.
	 */
	public static function get_tag_from_event( Event $event ): ?string {
		// Check we have a post and a post_id.
		if ( $event->object_type !== 'post' || $event->object_key === null ) {
			return null;
		}

		// Try to get the linked object from the post. This will return null if the post has been deleted.
		$linked_object = self::get_linked_object( $event->object_key );
		if ( $linked_object ) {
			// Convert the linked object to a string.
			return Types::value_to_string( $linked_object );
		}

		// Try to get the link from the event properties.
		$prop = $event->get_prop( 'link' );
		if ( $prop && $prop->val ) {
			// Convert the linked object to a string.
			return Types::value_to_string( $prop->val );
		}

		return null;
	}
}
